/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddEddit.java
 *
 * Created on Mar 3, 2012, 10:51:41 PM
 */
package storeapp;

import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.ComboBoxModel;
import storeapp.entity.Seller;

/**
 *
 * @author dalev
 */
public class AddEdit extends javax.swing.JDialog {

    public static final String TITLE_EDIT = "Add edit Order";
    private List<Seller> sellers;
    private String sellersvalue;

    /** Creates new form AddEddit */
    public AddEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle(TITLE_EDIT);
        initComponents();
        entityAddEditValues();
    }

    private void entityAddEditValues() {
        sellers = setEntityManager.createNamedQuery("Seller.findAll").getResultList();
        for (Seller a : sellers) {
            sellersvalue += a.getNameSeller();
        }
        text.setText(sellersvalue);
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("storedbPU").createEntityManager();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        text.setColumns(20);
        text.setRows(5);
        text.setName("text"); // NOI18N
        jScrollPane1.setViewportView(text);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddEdit dialog = new AddEdit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.persistence.EntityManager setEntityManager;
    private javax.swing.JTextArea text;
    // End of variables declaration//GEN-END:variables
}
