/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddEddit.java
 *
 * Created on Mar 3, 2012, 10:51:41 PM
 */
package storeapp;

import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.ComboBoxModel;
import storeapp.entity.OrderDetail;
import storeapp.entity.Seller;
import storeapp.tablemodels.OrderDetailsTableModel;

/**
 *
 * @author dalev
 */
public class AddEdit extends javax.swing.JDialog {

    public static final String TITLE_EDIT = "Add edit Order";
    private String sellersvalue;
    private List<OrderDetail> orderDetail;

    private OrderDetailsTableModel orderDetailsTableModel;

    /** Creates new form AddEddit */
    public AddEdit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle(TITLE_EDIT);
        orderDetailsTableModel = new OrderDetailsTableModel();
        initComponents();
        entityAddEditValues();
    }

    private void entityAddEditValues() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("storedbPU").createEntityManager();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderDetailsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        orderDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        orderDetailsTable.setName("orderDetailsTable"); // NOI18N
        jScrollPane1.setViewportView(orderDetailsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AddEdit dialog = new AddEdit(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderDetailsTable;
    private javax.persistence.EntityManager setEntityManager;
    // End of variables declaration//GEN-END:variables

    void setCustomOrderIdForEdit(Integer customOrderId) {
        orderDetailsTableModel.clear();
        int customerOrderId = customOrderId;
        orderDetail =  setEntityManager.createNamedQuery("OrderDetail.getGatAllByCustomerOrderId").setParameter("custom_order_id", customerOrderId).getResultList();
        for(OrderDetail od : orderDetail) {
            orderDetailsTableModel.add(od);
        }

        orderDetailsTable.setModel(orderDetailsTableModel);
    }
}
