/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StoreView.java
 *
 * Created on Mar 3, 2012, 7:01:42 PM
 */
package storeapp;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import org.jdesktop.application.Action;
import storeapp.entity.CustomOrder;
import storeapp.entity.Product;
import storeapp.session.UserSessionManager;
import storeapp.tablemodels.OrderModel;
import storeapp.tablemodels.OrdersTableModel;
import storeapp.tablemodels.ProductsTableModel;

/**
 *
 * @author dalev
 */
public class StoreView extends javax.swing.JFrame {

    private static final String APP_NAME = "StoreApp";
    public static final String PRODUCT_TABLE_TITLE = "Product";
    private String SELLER_CRUD_TAB_TITLE = "Seller";
    public static final int READ_ONLY_PRODUCTS_TABLE = 1;
    private EntityManager entityManager = Persistence.createEntityManagerFactory("storedbPU").createEntityManager();
    private LoginDialog loginDialog;
    private AddEdit addEdit;
    private List<CustomOrder> orders;
    private List<Product> allProducts;
    private OrdersTableModel ordersTableModel = new OrdersTableModel();
    private ProductsTableModel productsTableModel = new ProductsTableModel();
    private ProductCrudTable productCrud;
    private SellerCrudTable sellerCrud;

    /** Creates new form StoreView */
    public StoreView() {
        initComponents();
        setTitle(APP_NAME);
        loginDialog = new LoginDialog(this, true);
        loginDialog.addComponentListener(new ComponentAdapter() {


            @Override
            public void componentHidden(ComponentEvent e) {
                fetchCustomerOrdersBySellerId();
                fetchAllProducts();

                boolean isManager = UserSessionManager.getSingleton().isIsManager();
                if (isManager) {
                    tabPanel.removeTabAt(READ_ONLY_PRODUCTS_TABLE);
                    tabPanel.addTab(PRODUCT_TABLE_TITLE, productCrud);
                    tabPanel.addTab(SELLER_CRUD_TAB_TITLE, sellerCrud);
                }
            }
        });

        loginDialog.setEnityManager(entityManager);
        loginDialog.setVisible(true);
        addEdit = new AddEdit(this, true);

        productCrud = new ProductCrudTable();
        sellerCrud = new SellerCrudTable();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        LayerOrders = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        addOrderButton = new javax.swing.JButton();
        editOrderButton = new javax.swing.JButton();
        LayerProducts = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        tabPanel.setName("tabPanel"); // NOI18N

        LayerOrders.setName("LayerOrders"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        orderTable.setName("orderTable"); // NOI18N
        jScrollPane1.setViewportView(orderTable);

        jScrollPane1.setBounds(0, 0, 500, 150);
        LayerOrders.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(storeapp.StoreApp.class).getContext().getActionMap(StoreView.class, this);
        addOrderButton.setAction(actionMap.get("addEdit")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(storeapp.StoreApp.class).getContext().getResourceMap(StoreView.class);
        addOrderButton.setText(resourceMap.getString("addOrderButton.text")); // NOI18N
        addOrderButton.setName("addOrderButton"); // NOI18N
        addOrderButton.setBounds(340, 160, 118, 30);
        LayerOrders.add(addOrderButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        editOrderButton.setText(resourceMap.getString("editOrderButton.text")); // NOI18N
        editOrderButton.setName("editOrderButton"); // NOI18N
        editOrderButton.setBounds(250, 160, -1, -1);
        LayerOrders.add(editOrderButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tabPanel.addTab(resourceMap.getString("LayerOrders.TabConstraints.tabTitle"), LayerOrders); // NOI18N

        LayerProducts.setName("LayerProducts"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productsTable.setName("productsTable"); // NOI18N
        jScrollPane2.setViewportView(productsTable);

        jScrollPane2.setBounds(0, 0, 500, 160);
        LayerProducts.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tabPanel.addTab(resourceMap.getString("LayerProducts.TabConstraints.tabTitle"), LayerProducts); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StoreView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayerOrders;
    private javax.swing.JLayeredPane LayerProducts;
    private javax.swing.JButton addOrderButton;
    private javax.swing.JButton editOrderButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable productsTable;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables

    private void fetchCustomerOrdersBySellerId() {
        int userId = UserSessionManager.getSingleton().getUserId();
        orders = entityManager.createNamedQuery(CustomOrder.orderDetails).setParameter("userID", userId).getResultList();
        for (CustomOrder o : orders) {
            ordersTableModel.add(new OrderModel(o.getCustomOrderId(), o.getCustomer().getNameCustomer(), 3.f));
        }

        orderTable.setModel(ordersTableModel);

    }

    public void fetchAllProducts() {
        allProducts = entityManager.createNamedQuery(Product.getAll).getResultList();

        for (Product p : allProducts) {
            productsTableModel.add(p);
        }

        productsTable.setModel(productsTableModel);
        productsTable.setAutoCreateRowSorter(true);
    }

    @Action
    public void addEdit() {
        if (orderTable.getSelectedRowCount() != 0) {
            addEdit.setCustomOrderIdForEdit(orders.get(orderTable.getSelectedRow()).getCustomOrderId());
        }
        addEdit.setVisible(true);
    }
}
