/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StoreView.java
 *
 * Created on Mar 3, 2012, 7:01:42 PM
 */
package storeapp;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.jdesktop.application.Action;
import storeapp.entity.CustomOrder;
import storeapp.entity.Product;
import storeapp.entity.Seller;
import storeapp.session.UserSessionManager;
import storeapp.tablemodels.OrderModel;
import storeapp.tablemodels.OrdersTableModel;
import storeapp.tablemodels.ProductsTableModel;
import storeapp.tablemodels.SellerTableModel;

/**
 *
 * @author dalev
 */
public class StoreView extends javax.swing.JFrame {

    private static final String APP_NAME = "StoreApp";
    private EntityManager entityManager = Persistence.createEntityManagerFactory("storedbPU").createEntityManager();
    LoginDialog loginDialog;
    AddEdit addEdit;
    AddProductFrame addProductFrame;
    EditProductFrame editProductFrame;
    private List<CustomOrder> orders;
    private List<Product> allProducts;
    private OrdersTableModel ordersTableModel = new OrdersTableModel();
    private ProductsTableModel productsTableModel = new ProductsTableModel();
    private List<Seller> allSellers;
    private SellerTableModel sellerTableModel = new SellerTableModel();

    /** Creates new form StoreView */
    public StoreView() {
        initComponents();
        setTitle(APP_NAME);
//        Product p = new Product(1, 2, "Sapun", 3.4f, 34.4);
//        entityManager.getTransaction().begin();
//        entityManager.persist(p);
//        entityManager.getTransaction().commit();
        loginDialog = new LoginDialog(this, true);
        loginDialog.addComponentListener(new ComponentAdapter() {

            @Override
            public void componentHidden(ComponentEvent e) {
                fetchCustomerOrdersBySellerId();
                fetchAllProducts();
                fretcAllSellers();
                boolean isManager = UserSessionManager.getSingleton().isIsManager();
                if (isManager) {
                    editProductButton.setVisible(true);
                    addProductButton.setVisible(true);

                } else {
                    editProductButton.setVisible(false);
                    addProductButton.setVisible(false);
                    tabPanel.removeTabAt(2);
                }
            }
        });

        loginDialog.setEnityManager(entityManager);
        loginDialog.setVisible(true);
        addEdit = new AddEdit(this, true);
        addProductFrame = new AddProductFrame(this, true);
        editProductFrame = new EditProductFrame(this, true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        LayerOrders = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        addOrderButton = new javax.swing.JButton();
        editOrderButton = new javax.swing.JButton();
        LayerProducts = new javax.swing.JLayeredPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        editProductButton = new javax.swing.JButton();
        addProductButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        sellerTable = new javax.swing.JTable();
        editSellerButton = new javax.swing.JButton();
        addSellerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        tabPanel.setName("tabPanel"); // NOI18N

        LayerOrders.setName("LayerOrders"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        orderTable.setName("orderTable"); // NOI18N
        jScrollPane1.setViewportView(orderTable);

        jScrollPane1.setBounds(0, 0, 500, 150);
        LayerOrders.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(storeapp.StoreApp.class).getContext().getActionMap(StoreView.class, this);
        addOrderButton.setAction(actionMap.get("addEdit")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(storeapp.StoreApp.class).getContext().getResourceMap(StoreView.class);
        addOrderButton.setText(resourceMap.getString("addOrderButton.text")); // NOI18N
        addOrderButton.setName("addOrderButton"); // NOI18N
        addOrderButton.setBounds(340, 160, 118, 30);
        LayerOrders.add(addOrderButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        editOrderButton.setText(resourceMap.getString("editOrderButton.text")); // NOI18N
        editOrderButton.setName("editOrderButton"); // NOI18N
        editOrderButton.setBounds(250, 160, 51, 23);
        LayerOrders.add(editOrderButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tabPanel.addTab(resourceMap.getString("LayerOrders.TabConstraints.tabTitle"), LayerOrders); // NOI18N

        LayerProducts.setName("LayerProducts"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productsTable.setName("productsTable"); // NOI18N
        jScrollPane2.setViewportView(productsTable);

        jScrollPane2.setBounds(0, 0, 500, 160);
        LayerProducts.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        editProductButton.setAction(actionMap.get("EditProductFrameAction")); // NOI18N
        editProductButton.setText(resourceMap.getString("editProductButton.text")); // NOI18N
        editProductButton.setName("editProductButton"); // NOI18N
        editProductButton.setBounds(380, 170, 51, 23);
        LayerProducts.add(editProductButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        addProductButton.setAction(actionMap.get("AddProductFrame")); // NOI18N
        addProductButton.setText(resourceMap.getString("addProductButton.text")); // NOI18N
        addProductButton.setName("addProductButton"); // NOI18N
        addProductButton.setBounds(300, 170, 51, 23);
        LayerProducts.add(addProductButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setAction(actionMap.get("DeleteProduct")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setBounds(200, 170, 63, 23);
        LayerProducts.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tabPanel.addTab(resourceMap.getString("LayerProducts.TabConstraints.tabTitle"), LayerProducts); // NOI18N

        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        sellerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sellerTable.setName("sellerTable"); // NOI18N
        jScrollPane3.setViewportView(sellerTable);
        sellerTable.getColumnModel().getColumn(0).setHeaderValue(resourceMap.getString("sellerTable.columnModel.title0")); // NOI18N
        sellerTable.getColumnModel().getColumn(1).setHeaderValue(resourceMap.getString("sellerTable.columnModel.title1")); // NOI18N
        sellerTable.getColumnModel().getColumn(2).setHeaderValue(resourceMap.getString("sellerTable.columnModel.title2")); // NOI18N
        sellerTable.getColumnModel().getColumn(3).setHeaderValue(resourceMap.getString("sellerTable.columnModel.title3")); // NOI18N

        jScrollPane3.setBounds(10, 0, 490, 160);
        jLayeredPane1.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        editSellerButton.setText(resourceMap.getString("editSellerButton.text")); // NOI18N
        editSellerButton.setName("editSellerButton"); // NOI18N
        editSellerButton.setBounds(390, 170, 51, 23);
        jLayeredPane1.add(editSellerButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        addSellerButton.setText(resourceMap.getString("addSellerButton.text")); // NOI18N
        addSellerButton.setName("addSellerButton"); // NOI18N
        addSellerButton.setBounds(310, 170, 51, 23);
        jLayeredPane1.add(addSellerButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tabPanel.addTab(resourceMap.getString("jLayeredPane1.TabConstraints.tabTitle"), jLayeredPane1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StoreView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayerOrders;
    private javax.swing.JLayeredPane LayerProducts;
    private javax.swing.JButton addOrderButton;
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton addSellerButton;
    private javax.swing.JButton editOrderButton;
    private javax.swing.JButton editProductButton;
    private javax.swing.JButton editSellerButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable orderTable;
    private javax.swing.JTable productsTable;
    private javax.swing.JTable sellerTable;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables

    private void fetchCustomerOrdersBySellerId() {
        int userId = UserSessionManager.getSingleton().getUserId();
        orders = entityManager.createNamedQuery(CustomOrder.orderDetails).setParameter("userID", userId).getResultList();
        for (CustomOrder o : orders) {
            ordersTableModel.add(new OrderModel(o.getCustomOrderId(), o.getCustomer().getNameCustomer(), 3.f));
        }

        orderTable.setModel(ordersTableModel);

    }

    public void fetchAllProducts() {
        allProducts = entityManager.createNamedQuery(Product.getAll).getResultList();

        for (Product p : allProducts) {
            productsTableModel.add(p);
        }

        productsTable.setModel(productsTableModel);
        productsTable.setAutoCreateRowSorter(true);

    }

    public void fretcAllSellers() {
        allSellers = entityManager.createNamedQuery(Seller.getAllSellers).getResultList();

        for (Seller s : allSellers) {
            sellerTableModel.add(s);
        }
        sellerTable.setModel(sellerTableModel);

    }

    @Action
    public void addEdit() {
        if (orderTable.getSelectedRowCount() != 0) {
            addEdit.setCustomOrderIdForEdit(orders.get(orderTable.getSelectedRow()).getCustomOrderId());
        }
        addEdit.setVisible(true);
    }

    @Action
    public void AddProductFrame() {
        addProductFrame.setVisible(true);
    }

    @Action
    public void EditProductFrameAction() {
        if (productsTable.getSelectedRowCount() != 0) {
           editProductFrame.setProductIdForEdit(allProducts.get(productsTable.getSelectedRow()).getProductId());
           
        }
        editProductFrame.setVisible(true);
    }

    @Action
    public void DeleteProduct() {
         if (productsTable.getSelectedRowCount() != 0) {
         int idProductForDelete =   allProducts.get(productsTable.getSelectedRow()).getProductId();
         allProducts = entityManager.createNamedQuery("Product.findByProductId").setParameter("productId", idProductForDelete).getResultList();
         entityManager.getTransaction().begin();
         entityManager.remove(allProducts);
         entityManager.flush();
         entityManager.getTransaction().commit();

        }
    
    }
}
